### ISSUE TITLE
What is the PytorchHelpers package in transition_system.py?

### ISSUE THREAD

**Issue by qiusg** [mdtux89/amr-eager-multilingual#1]

**Comment by mdtux89** [comment]
The confusion probably comes from the naming of the 'pytorch' package that is used in this repo. At the time the https://pytorch.org didn't exist, the one I use here is a python wrapper around Torch: https://github.com/hughperkins/pytorch. PytorchHelpers is part of that repo.

**Comment by qiusg** [comment]
Oh, I see it. 
But when I run setup.py in this pytorch repo,  an error occurred:
"""Please set environment variable TORCH_INSTALL to the directory of your torch/install directory"""
Seems like it need to install torch at first, so I install torch by pip install torch, but it only support version 0.1.1 and 0.1.2, which is too old to install successfully.
Is there any other way to quickly install PyTorch used in your code? Or other new repo to replace PyTorch?

**Comment by mdtux89** [comment]
I am not aware of it sorry. Sadly, I don't have capacity to update the repo with up to date packages.
